In [2]:
import numpy as np

In [3]:
#1.Multiply 2 matrices.

In [6]:
x=np.array([[1,4,3],[3,5,6],[6,7,9]])
x

array([[1, 4, 3],
       [3, 5, 6],
       [6, 7, 9]])

In [17]:
y=np.array([[1,2,5],[6,7,3,],[4,7,9]])
y

array([[1, 2, 5],
       [6, 7, 3],
       [4, 7, 9]])

In [19]:
mul=x*y
mul

array([[ 1,  8, 15],
       [18, 35, 18],
       [24, 49, 81]])

In [20]:
#2.Extract all numbers divisible by 3 from the array?

In [4]:
import numpy as np

In [5]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
arr[(arr%3==0)]

array([ 0,  3,  6,  9, 12])

In [9]:
#3.How to get the unique common items between two python numpy arrays?

In [10]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [11]:
b=np.array([7,2,1,2,7,4,9,4,9,8])
b

array([7, 2, 1, 2, 7, 4, 9, 4, 9, 8])

In [12]:
a[np.where(a==b)]

array([2, 2, 4, 4])

In [13]:
#4. How to remove from one array those items that exist in another?

In [23]:
a1 = np.array([1,2,3,4,5,11,22,33,44,55])
a1

array([ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55])

In [24]:
b1 = np.array([5,6,7,8,9,10,11])
b1

array([ 5,  6,  7,  8,  9, 10, 11])

In [26]:
np.setdiff1d(a1,b1)

array([ 1,  2,  3,  4, 22, 33, 44, 55])

In [27]:
#5. How to get the positions where elements of two arrays match?

In [28]:
a2 = np.array([1,2,3,2,3,4,3,4,5,6])
a2

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [29]:
b2 = np.array([7,2,10,2,7,4,9,4,9,8])
b2

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [30]:
a2[np.where(a2==b2)]

array([2, 2, 4, 4])

In [34]:
#6. How to create a 2D array containing random floats between 10 and 25?Create a 2D array of shape 5x3 to contain random decimal numbers between 10 and 25.

In [38]:
rand_arr=np.random.randint(10,25,(5,3))
rand_arr

array([[13, 16, 20],
       [18, 16, 12],
       [21, 24, 19],
       [18, 19, 14],
       [17, 10, 19]])

In [39]:
#7. Take a string as input. Create a new string that is the reverse of the first string.

In [40]:
A ="Hello"[::-1]

In [42]:
print (A)

olleH


In [43]:
#8.Write a Python program to remove the first occurrence of a specified element  (ex 7 ) from an array.Repeat the same for all occurrences of 7.

In [71]:
from array import *

In [68]:
arr_1=array("i",[1,7,5,7,3,1,9,7])
arr_1

[1, 7, 5, 7, 3, 1, 9, 7]

In [72]:
arr_1.remove(7)

In [73]:
print(arr_1)

[1, 5, 3, 1, 9]


In [74]:
#9. Write a Python program that iterate over elements repeating each as many times as its count.

In [75]:
from collections import Counter

In [79]:
c=Counter(p=4,q=2,r=5,s=-1,t=0)
print(list(c.elements()))

['p', 'p', 'p', 'p', 'q', 'q', 'r', 'r', 'r', 'r', 'r']


In [80]:
#10. Write a Python program to find the occurrences of 10 most common words in a given text.

In [83]:
from collections import Counter

In [84]:
import re

In [85]:
text="""The Python Software Foundation (PSF) is a 501(c)(3) non-profit 
corporation that holds the intellectual property rights behind
the Python programming language. We manage the open source licensing 
for Python version 2.1 and later and own and protect the trademarks 
associated with Python. We also run the North American PyCon conference 
annually, support other Python conferences around the world, and 
fund Python related development with our grants program and by funding 
special projects."""

In [86]:
words = re.findall("\w+",text)

In [87]:
print(Counter(words).most_common(10))

[('Python', 6), ('the', 6), ('and', 5), ('We', 2), ('with', 2), ('The', 1), ('Software', 1), ('Foundation', 1), ('PSF', 1), ('is', 1)]
